#!/bin/bash

# default values
SERVERURL=csc-daq
SERVERPORT=20200
SERVERAPP=emu::daq::manager::Application
SERVERAPPINSTANCE=0
VERBOSITY=0
PARAMETER=stateName
TYPE=xsd:string

# user's options
while [[ $1 = -* ]]; do
    case $1 in 
	-A ) SERVERAPP=$2
	    shift ;;
	-c ) CREDITS=$2
	    shift ;;
	-P ) PARAMETER=$2
	    shift ;;
	-T ) TYPE=$2
	    shift ;;
	-I ) SERVERAPPINSTANCE=$2
	    shift ;;
	-L ) SERVERAPPLID=$2
	    shift ;;
	-p ) SERVERPORT=$2
	    shift ;;
	-u ) SERVERURL=$2
	    shift ;;
	-v ) VERBOSITY=1 ;;
	*  ) 
	    echo 'Usage:'
	    echo '------'
	    echo '    emuParameterGet [-u url] [-p port]'
	    echo '                    [-A application] [-I app_instance] [-P parameter_name] [-T parameter_type]'
	    echo '                    [-v]'
	    echo
	    echo '  option   meaning                            default'
	    echo '  ------   -------                            -------'
	    echo '      -A   application                        emu::daq::manager::Application'
	    echo '      -P   parameter name                     stateName'
	    echo '      -T   parameter type                     xsd:string'
	    echo '      -h   print help                         do not print help'
	    echo '      -I   server application instance        0'
	    echo '      -L   server application lid             <not used; application instance used instead>'
	    echo '      -p   port                               20200'
	    echo '      -u   url                                csc-daq'
	    echo '      -v   verbose                            not verbose'
	    echo
	    echo 'Example:'
	    echo '--------'
	    echo '    emuParameterGet -u csc-daq01.cms -p 9999 -A jobcontrol::Application -L 10'
	    exit 1 ;;
    esac
    shift
done

if [[ ${#SERVERAPPLID} == 0 ]]; then
    HEADER="\"SOAPAction: urn:xdaq-application:class=$SERVERAPP,instance=$SERVERAPPINSTANCE\""
else
    HEADER="\"SOAPAction: urn:xdaq-application:lid=$SERVERAPPLID\""
fi

MESSAGE="\"<soap-env:Envelope soap-env:encodingStyle=\\\"http://schemas.xmlsoap.org/soap/encoding/\\\" xmlns:soap-env=\\\"http://schemas.xmlsoap.org/soap/envelope/\\\" xmlns:xsd=\\\"http://www.w3.org/2001/XMLSchema\\\" xmlns:xsi=\\\"http://www.w3.org/2001/XMLSchema-instance\\\" xmlns:soapenc=\\\"http://schemas.xmlsoap.org/soap/encoding/\\\"><soap-env:Header/><soap-env:Body><xdaq:ParameterGet xmlns:xdaq=\\\"urn:xdaq-soap:3.0\\\"><xapp:properties xmlns:xapp=\\\"urn:xdaq-application:$SERVERAPP\\\" xsi:type=\\\"soapenc:Struct\\\"><xapp:$PARAMETER xsi:type=\\\"$TYPE\\\"/></xapp:properties></xdaq:ParameterGet></soap-env:Body></soap-env:Envelope>\""

WRITEOUT=""
if [[ $VERBOSITY = "1" ]]; then
    WRITEOUT="--write-out \"\n\nGot %{size_download} bytes in total (%{size_header} in header) in %{time_total} s.\n\""
    echo "Command:"
    echo curl -H $HEADER http://$SERVERURL:$SERVERPORT $WRITEOUT -d $MESSAGE
    echo ""
    echo "Reply:"
fi

eval curl -H $HEADER http://$SERVERURL:$SERVERPORT $WRITEOUT -d $MESSAGE | sed -u -e :a -e 'N;s/\n/ /g; ta'| sed -u -e :a -e 'N;s/\n/ /g; ta'| sed -u 's/<[ ]*\([^<> ]\+:\)\?\([^<> ]\+\)\(\([ ]\+[^<> ]\+\)*[ ]*\)>\([^<>]\+\)<\//<\1[1;34m\2[0m\3>[1;31m\5[0m<\//g'
echo ""
