#!/bin/bash

# Browse raw data files in hexadecimal format, highlighting unique DDU header and/or trailer words

SEDPATTERNS=""

while [[ $1 = -* ]]; do
    case $1 in 
	-H ) SEDPATTERNS="$SEDPATTERNS -e 's/ \(800000018000[^ ][^ ][^ ][^ ]\) / [1;34m\1[0m /g'"
	    shift ;;
	-T ) SEDPATTERNS="$SEDPATTERNS -e 's/ \(8000ffff80008000\) / [1;31m\1[0m /g'"
	    shift ;;
	-M ) SEDPATTERNS="$SEDPATTERNS -e ':a;N;\$!ba;s/\([^ ]\{7\} \)9\([^ ][^ ][^ ]\)9\([^ ][^ ][^ ]\)9\([^ ][^ ][^ ]\)9\([^ ][^ ][^ ]  >[^\n]\{8\}<\n[^ ]\{7\} \)a\([^ ][^ ][^ ]\)a\([^ ][^ ][^ ]\)a\([^ ][^ ][^ ]\)a/\1[1;35m9[0m\2[1;35m9[0m\3[1;35m9[0m\4[1;35m9[0m\5[1;35ma[0m\6[1;35ma[0m\7[1;35ma[0m\8[1;35ma[0m/g' -e 's/\([^ ]\{7\} \)f\([^ ][^ ][^ ]\)f\([^ ][^ ][^ ]\)f\([^ ][^ ][^ ]\)f\([^ ][^ ][^ ]  >[^\n]\{8\}<\n[^ ]\{7\} \)e\([^ ][^ ][^ ]\)e\([^ ][^ ][^ ]\)e\([^ ][^ ][^ ]\)e/\1[1;36mf[0m\2[1;36mf[0m\3[1;36mf[0m\4[1;36mf[0m\5[1;36me[0m\6[1;36me[0m\7[1;36me[0m\8[1;36me[0m/g'"
	    # $! needed to be escaped in the sed command above or else it was interpreted by 'eval' below...
	    shift ;;
	*  ) 
	    echo 'Usage: '
	    echo "    $0" '[-H] [-T]  [-M] raw_data_file'
	    echo
	    echo '  option   meaning'
	    echo '  ------   -------'
	    echo '      -H   highlight unique DDU header word'
	    echo '      -T   highlight unique DDU trailer word'
	    echo '      -M   highlight DMB header and trailer (slow on big files)'
	    exit 1 ;;
    esac
done

if [ ${#SEDPATTERNS} != 0 ]; then
    eval "od -Ad -tx8z -w8 $1 | sed $SEDPATTERNS | less -R"
else
    od -Ad -tx8z -w8 $1 | less
fi

