//
// File generated by /opt/cern/root/bin/rootcint at Tue Feb 14 19:12:40 2006.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "CObjectDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void CObject_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_CObject(void *p = 0);
   static void *newArray_CObject(Long_t size);
   static void delete_CObject(void *p);
   static void deleteArray_CObject(void *p);
   static void destruct_CObject(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::CObject*)
   {
      ::CObject *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CObject >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CObject", ::CObject::Class_Version(), "/home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/include/CObject.hh", 24,
                  typeid(::CObject), DefineBehavior(ptr, ptr),
                  &::CObject::Dictionary, isa_proxy, 0,
                  sizeof(::CObject) );
      instance.SetNew(&new_CObject);
      instance.SetNewArray(&newArray_CObject);
      instance.SetDelete(&delete_CObject);
      instance.SetDeleteArray(&deleteArray_CObject);
      instance.SetDestructor(&destruct_CObject);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::CObject*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *CObject::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CObject::Class_Name()
{
   return "CObject";
}

//______________________________________________________________________________
const char *CObject::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::CObject*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CObject::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::CObject*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CObject::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::CObject*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CObject::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::CObject*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CObject::Streamer(TBuffer &R__b)
{
   // Stream an object of class CObject.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void CObject::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class CObject.

      TClass *R__cl = ::CObject::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fTObject", &fTObject);
      R__insp.Inspect(R__cl, R__parent, "*fInputSource", &fInputSource);
      R__insp.Inspect(R__cl, R__parent, "fName", &fName);
      fName.ShowMembers(R__insp, strcat(R__parent,"fName.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fPath", &fPath);
      fPath.ShowMembers(R__insp, strcat(R__parent,"fPath.")); R__parent[R__ncp] = 0;
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CObject(void *p) {
      return  p ? new(p) ::CObject : new ::CObject;
   }
   static void *newArray_CObject(Long_t size) {
      return new ::CObject[size];
   }
   // Wrapper around operator delete
   static void delete_CObject(void *p) {
      delete ((::CObject*)p);
   }
   static void deleteArray_CObject(void *p) {
      delete [] ((::CObject*)p);
   }
   static void destruct_CObject(void *p) {
      typedef ::CObject current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CObject

/********************************************************
* /home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/src/common/CObjectDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableCObjectDict();

extern "C" void G__set_cpp_environmentCObjectDict() {
  G__add_macro("G__CINTVERSION=50160005");
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/include/CObject.hh");
  G__cpp_reset_tagtableCObjectDict();
}
class G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondICObjectDictdOcc_tag {};

void* operator new(size_t size,G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondICObjectDictdOcc_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondICObjectDictdOcc_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondICObjectDictdOcc() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevCObjectDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CObject */
static int G__CObjectDict_261_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   CObject *p=NULL;
   if(G__getaryconstruct()) {
     if(G__PVOID==G__getgvp()) {
       p=new CObject[G__getaryconstruct()];
     } else {
       p=new CObject[G__getaryconstruct()];
     }
   }
   else p=new CObject;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__CObjectDictLN_CObject);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   CObject *p=NULL;
      p = new CObject((TObject*)G__int(libp->para[0]),(const TObject*)G__int(libp->para[1]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__CObjectDictLN_CObject);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   CObject *p=NULL;
      p = new CObject(*(CObject*)libp->para[0].ref);
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__CObjectDictLN_CObject);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        const CObject& obj=((CObject*)(G__getstructoffset()))->operator=(*(CObject*)libp->para[0].ref);
         result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((const CObject*)(G__getstructoffset()))->GetPath());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((const CObject*)(G__getstructoffset()))->GetName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((const CObject*)(G__getstructoffset()))->GetTitle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((const CObject*)(G__getstructoffset()))->IsSortable());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,107,(long)((const CObject*)(G__getstructoffset()))->Hash());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((const CObject*)(G__getstructoffset()))->IsEqual((const TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const CObject*)(G__getstructoffset()))->Compare((const TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const CObject*)(G__getstructoffset()))->GetTObject());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const CObject*)(G__getstructoffset()))->GetInputSource());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->SetPath(*((TString*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->SetTObject((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->SetInputSource((const TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->Draw((Option_t*)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->Draw();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->Paint((Option_t*)G__int(libp->para[0]));
      break;
   case 0:
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->Paint();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->ReadObject();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)CObject::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)CObject::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)CObject::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      CObject::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const CObject*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((CObject*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)CObject::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)CObject::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)CObject::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CObjectDict_261_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)CObject::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CObject G__TCObject;
static int G__CObjectDict_261_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (CObject *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (CObject *)((G__getstructoffset())+sizeof(CObject)*i);
   else  delete (CObject *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CObject */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCObjectDict {
 public:
  G__Sizep2memfuncCObjectDict() {p=&G__Sizep2memfuncCObjectDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCObjectDict::*p)();
};

size_t G__get_sizep2memfuncCObjectDict()
{
  G__Sizep2memfuncCObjectDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCObjectDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__CObjectDictLN_CObject))) {
     CObject *G__Lderived;
     G__Lderived=(CObject*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CObjectDictLN_CObject),G__get_linked_tagnum(&G__CObjectDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCObjectDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("ULong_t",107,-1,0,
-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Bool_t",103,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,
-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__CObjectDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: CObjectDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CObjectDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CObjectDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: CObjectDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CObjectDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CObjectDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: CObjectDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CObject */
static void G__setup_memvarCObject(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__CObjectDictLN_CObject));
   { CObject *p; p=(CObject*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__CObjectDictLN_TObject),-1,-1,2,"fTObject=",0,"Original TObject.");
   G__memvar_setup((void*)NULL,85,0,1,G__get_linked_tagnum(&G__CObjectDictLN_TObject),-1,-1,2,"fInputSource=",0,"Input source. TFile, TMapFile, TSocket.");
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__CObjectDictLN_TString),-1,-1,2,"fName=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__CObjectDictLN_TString),-1,-1,2,"fPath=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__CObjectDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCObjectDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCObject(void) {
   /* CObject */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__CObjectDictLN_CObject));
   G__memfunc_setup("GetNewObj",869,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__CObjectDictLN_TObject),-1,0,2,1,4,0,
"C - - 10 - - U 'TObject' - 10 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("free",418,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ResetAllkCanDelete",1772,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TVirtualPad' - 0 - pad",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CObject",666,G__CObjectDict_261_4_0,105,G__get_linked_tagnum(&G__CObjectDictLN_CObject),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CObject",666,G__CObjectDict_261_5_0,105,G__get_linked_tagnum(&G__CObjectDictLN_CObject),-1,0,2,1,1,0,
"U 'TObject' - 0 - obj U 'TObject' - 10 - inputsource",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CObject",666,G__CObjectDict_261_6_0,105,G__get_linked_tagnum(&G__CObjectDictLN_CObject),-1,0,1,1,1,0,"u 'CObject' - 11 - cobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("operator=",937,G__CObjectDict_261_7_0,117,G__get_linked_tagnum(&G__CObjectDictLN_CObject),-1,1,1,1,1,0,"u 'CObject' - 11 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetPath",685,G__CObjectDict_261_8_0,67,-1,-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetName",673,G__CObjectDict_261_9_0,67,-1,-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetTitle",802,G__CObjectDict_261_0_1,67,-1,-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("IsSortable",1016,G__CObjectDict_261_1_1,103,-1,G__defined_typename("Bool_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Hash",388,G__CObjectDict_261_2_1,107,-1,G__defined_typename("ULong_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("IsEqual",692,G__CObjectDict_261_3_1,103,-1,G__defined_typename("Bool_t"),0,1,1,1,8,"U 'TObject' - 10 - obj2",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Compare",711,G__CObjectDict_261_4_1,105,-1,G__defined_typename("Int_t"),0,1,1,1,8,"U 'TObject' - 10 - obj",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetTObject",971,G__CObjectDict_261_5_1,85,G__get_linked_tagnum(&G__CObjectDictLN_TObject),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetInputSource",1441,G__CObjectDict_261_6_1,85,G__get_linked_tagnum(&G__CObjectDictLN_TObject),-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SetPath",697,G__CObjectDict_261_7_1,121,-1,-1,0,1,1,1,0,"u 'TString' - 0 - path",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SetTObject",983,G__CObjectDict_261_8_1,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SetInputSource",1453,G__CObjectDict_261_9_1,121,-1,-1,0,1,1,1,0,"U 'TObject' - 10 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Draw",398,G__CObjectDict_261_0_2,121,-1,-1,0,1,1,1,0,"C - 'Option_t' 10 \"\" option",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Paint",508,G__CObjectDict_261_1_2,121,-1,-1,0,1,1,1,0,"C - 'Option_t' 10 \"\" option",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ReadObject",979,G__CObjectDict_261_2_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Class",502,G__CObjectDict_261_3_2,85,G__get_linked_tagnum(&G__CObjectDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&CObject::Class),0);
   G__memfunc_setup("Class_Name",982,G__CObjectDict_261_4_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&CObject::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__CObjectDict_261_5_2,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&CObject::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__CObjectDict_261_6_2,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&CObject::Dictionary),0);
   G__memfunc_setup("IsA",253,G__CObjectDict_261_7_2,85,G__get_linked_tagnum(&G__CObjectDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__CObjectDict_261_8_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__CObjectDict_261_9_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__CObjectDict_261_0_3,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__CObjectDict_261_1_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&CObject::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__CObjectDict_261_2_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&CObject::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__CObjectDict_261_3_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&CObject::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__CObjectDict_261_4_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&CObject::DeclFileLine),0);
   // automatic destructor
   G__memfunc_setup("~CObject",792,G__CObjectDict_261_5_3,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCObjectDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCObjectDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCObjectDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__CObjectDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_TVirtualPad = { "TVirtualPad" , 99 , -1 };
G__linked_taginfo G__CObjectDictLN_CObject = { "CObject" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCObjectDict() {
  G__CObjectDictLN_TClass.tagnum = -1 ;
  G__CObjectDictLN_TBuffer.tagnum = -1 ;
  G__CObjectDictLN_TMemberInspector.tagnum = -1 ;
  G__CObjectDictLN_TObject.tagnum = -1 ;
  G__CObjectDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__CObjectDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CObjectDictLN_TString.tagnum = -1 ;
  G__CObjectDictLN_TVirtualPad.tagnum = -1 ;
  G__CObjectDictLN_CObject.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCObjectDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__CObjectDictLN_TClass);
   G__get_linked_tagnum(&G__CObjectDictLN_TBuffer);
   G__get_linked_tagnum(&G__CObjectDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__CObjectDictLN_TObject);
   G__get_linked_tagnum(&G__CObjectDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__CObjectDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__CObjectDictLN_TString);
   G__get_linked_tagnum(&G__CObjectDictLN_TVirtualPad);
   G__tagtable_setup(G__get_linked_tagnum(&G__CObjectDictLN_CObject),sizeof(CObject),-1,65280,(char*)NULL,G__setup_memvarCObject,G__setup_memfuncCObject);
}
extern "C" void G__cpp_setupCObjectDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCObjectDict()");
  G__set_cpp_environmentCObjectDict();
  G__cpp_setup_tagtableCObjectDict();

  G__cpp_setup_inheritanceCObjectDict();

  G__cpp_setup_typetableCObjectDict();

  G__cpp_setup_memvarCObjectDict();

  G__cpp_setup_memfuncCObjectDict();
  G__cpp_setup_globalCObjectDict();
  G__cpp_setup_funcCObjectDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCObjectDict();
  return;
}
class G__cpp_setup_initCObjectDict {
  public:
    G__cpp_setup_initCObjectDict() { G__add_setup_func("CObjectDict",(G__incsetup)(&G__cpp_setupCObjectDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCObjectDict() { G__remove_setup_func("CObjectDict"); }
};
G__cpp_setup_initCObjectDict G__cpp_setup_initializerCObjectDict;

