//
// File generated by /opt/cern/root/bin/rootcint at Tue Feb 14 19:12:39 2006.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "HistoDisplayDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void HistoDisplay_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_HistoDisplay(void *p);
   static void deleteArray_HistoDisplay(void *p);
   static void destruct_HistoDisplay(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::HistoDisplay*)
   {
      ::HistoDisplay *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::HistoDisplay >(0);
      static ::ROOT::TGenericClassInfo 
         instance("HistoDisplay", ::HistoDisplay::Class_Version(), "/home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/include/HistoDisplay.hh", 85,
                  typeid(::HistoDisplay), DefineBehavior(ptr, ptr),
                  &::HistoDisplay::Dictionary, isa_proxy, 0,
                  sizeof(::HistoDisplay) );
      instance.SetDelete(&delete_HistoDisplay);
      instance.SetDeleteArray(&deleteArray_HistoDisplay);
      instance.SetDestructor(&destruct_HistoDisplay);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::HistoDisplay*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *HistoDisplay::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *HistoDisplay::Class_Name()
{
   return "HistoDisplay";
}

//______________________________________________________________________________
const char *HistoDisplay::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::HistoDisplay*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int HistoDisplay::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::HistoDisplay*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void HistoDisplay::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::HistoDisplay*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *HistoDisplay::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::HistoDisplay*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void HistoDisplay::Streamer(TBuffer &R__b)
{
   // Stream an object of class HistoDisplay.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void HistoDisplay::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class HistoDisplay.

      TClass *R__cl = ::HistoDisplay::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fMenuBar", &fMenuBar);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarLayout", &fMenuBarLayout);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarItemLayout", &fMenuBarItemLayout);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarHelpLayout", &fMenuBarHelpLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFileMenu", &fFileMenu);
      R__insp.Inspect(R__cl, R__parent, "*fNewCascadeMenu", &fNewCascadeMenu);
      R__insp.Inspect(R__cl, R__parent, "*fListTreeMenu", &fListTreeMenu);
      R__insp.Inspect(R__cl, R__parent, "*fSortCascadeMenu", &fSortCascadeMenu);
      R__insp.Inspect(R__cl, R__parent, "*fConnectMenu", &fConnectMenu);
      R__insp.Inspect(R__cl, R__parent, "*fHelpMenu", &fHelpMenu);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarSeparator", &fMenuBarSeparator);
      R__insp.Inspect(R__cl, R__parent, "*fMenuBarSeparatorLayout", &fMenuBarSeparatorLayout);
      R__insp.Inspect(R__cl, R__parent, "*fMainFrame", &fMainFrame);
      R__insp.Inspect(R__cl, R__parent, "*fMainFrameLayout", &fMainFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "LightYellow", &LightYellow);
      R__insp.Inspect(R__cl, R__parent, "*fTitleFrame", &fTitleFrame);
      R__insp.Inspect(R__cl, R__parent, "*fTitleFrameLayout", &fTitleFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fTitleLabel", &fTitleLabel);
      R__insp.Inspect(R__cl, R__parent, "*fTitleLabelLayout", &fTitleLabelLayout);
      R__insp.Inspect(R__cl, R__parent, "fTextGC", &fTextGC);
      R__insp.Inspect(R__cl, R__parent, "*fPicBut", &fPicBut);
      R__insp.Inspect(R__cl, R__parent, "*fPictLayout", &fPictLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameFrame", &fFileNameFrame);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameFrameLayout", &fFileNameFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fRaButMFile", &fRaButMFile);
      R__insp.Inspect(R__cl, R__parent, "*fRaButRFile", &fRaButRFile);
      R__insp.Inspect(R__cl, R__parent, "*fRaButSocket", &fRaButSocket);
      R__insp.Inspect(R__cl, R__parent, "*fRaButSOAP", &fRaButSOAP);
      R__insp.Inspect(R__cl, R__parent, "*fRaButLayout", &fRaButLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameLabel", &fFileNameLabel);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameLabelLayout", &fFileNameLabelLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFileOpenFrame", &fFileOpenFrame);
      R__insp.Inspect(R__cl, R__parent, "*fFileOpenFrameLayout", &fFileOpenFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameTextEntry", &fFileNameTextEntry);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameTextEntryLayout", &fFileNameTextEntryLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameBuffer", &fFileNameBuffer);
      R__insp.Inspect(R__cl, R__parent, "*fRefNameBuffer", &fRefNameBuffer);
      R__insp.Inspect(R__cl, R__parent, "*fDynRefNameBuffer", &fDynRefNameBuffer);
      R__insp.Inspect(R__cl, R__parent, "*fReadFileButton", &fReadFileButton);
      R__insp.Inspect(R__cl, R__parent, "*fReadFileButtonLayout", &fReadFileButtonLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameButtonFrame", &fFileNameButtonFrame);
      R__insp.Inspect(R__cl, R__parent, "*fFileNameButtonFrameLayout", &fFileNameButtonFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fChooseFileButton", &fChooseFileButton);
      R__insp.Inspect(R__cl, R__parent, "*fChooseFileButtonLayout", &fChooseFileButtonLayout);
      R__insp.Inspect(R__cl, R__parent, "*fClearFileNameButton", &fClearFileNameButton);
      R__insp.Inspect(R__cl, R__parent, "*fClearFileNameButtonLayout", &fClearFileNameButtonLayout);
      R__insp.Inspect(R__cl, R__parent, "*fListTreeMainFrame", &fListTreeMainFrame);
      R__insp.Inspect(R__cl, R__parent, "*fListTreeMainFrameLayout", &fListTreeMainFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fHistoListFrame", &fHistoListFrame);
      R__insp.Inspect(R__cl, R__parent, "*fRefListFrame", &fRefListFrame);
      R__insp.Inspect(R__cl, R__parent, "*fHistoListFrameLayout", &fHistoListFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fRefListFrameLayout", &fRefListFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fTGCanvas", &fTGCanvas);
      R__insp.Inspect(R__cl, R__parent, "*fTGCanvasLayout", &fTGCanvasLayout);
      R__insp.Inspect(R__cl, R__parent, "*fHistoListTree", &fHistoListTree);
      R__insp.Inspect(R__cl, R__parent, "*fRefListTree", &fRefListTree);
      R__insp.Inspect(R__cl, R__parent, "REF_FLAG", &REF_FLAG);
      R__insp.Inspect(R__cl, R__parent, "*fListButtonFrame", &fListButtonFrame);
      R__insp.Inspect(R__cl, R__parent, "*fListButtonFrameLayout", &fListButtonFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fChButtonAutoUpdate", &fChButtonAutoUpdate);
      R__insp.Inspect(R__cl, R__parent, "*fChButtonAutoUpdateLayout", &fChButtonAutoUpdateLayout);
      R__insp.Inspect(R__cl, R__parent, "AutoUpdate", &AutoUpdate);
      R__insp.Inspect(R__cl, R__parent, "*fFrequencyFrame", &fFrequencyFrame);
      R__insp.Inspect(R__cl, R__parent, "*fFrequencyFrameLayout", &fFrequencyFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fFrequencyLabel", &fFrequencyLabel);
      R__insp.Inspect(R__cl, R__parent, "*fFrequencyTextEntry", &fFrequencyTextEntry);
      R__insp.Inspect(R__cl, R__parent, "*fFrequencyTextBuffer", &fFrequencyTextBuffer);
      R__insp.Inspect(R__cl, R__parent, "*fControlButtonFrame", &fControlButtonFrame);
      R__insp.Inspect(R__cl, R__parent, "*fControlButtonFrameLayout", &fControlButtonFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fButtonFrame", &fButtonFrame);
      R__insp.Inspect(R__cl, R__parent, "*fButtonFrameLayout", &fButtonFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fButtonLayout", &fButtonLayout);
      R__insp.Inspect(R__cl, R__parent, "*fStartHistoButton", &fStartHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fPauseHistoButton", &fPauseHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fRestartHistoButton", &fRestartHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fClearHistoButton", &fClearHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fStopHistoButton", &fStopHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fHistoButtonGFrame", &fHistoButtonGFrame);
      R__insp.Inspect(R__cl, R__parent, "*fHistoButtonGFrameLayout", &fHistoButtonGFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fHistoButtonFrame", &fHistoButtonFrame);
      R__insp.Inspect(R__cl, R__parent, "*fHistoButtonFrameLayout", &fHistoButtonFrameLayout);
      R__insp.Inspect(R__cl, R__parent, "*fHistoButtonLayout", &fHistoButtonLayout);
      R__insp.Inspect(R__cl, R__parent, "*fZeroHistoButton", &fZeroHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fUnZeroHistoButton", &fUnZeroHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fRefHistoButton", &fRefHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fContentHistoButton", &fContentHistoButton);
      R__insp.Inspect(R__cl, R__parent, "*fStatusBar", &fStatusBar);
      R__insp.Inspect(R__cl, R__parent, "*fSelectedItem", &fSelectedItem);
      R__insp.Inspect(R__cl, R__parent, "*PadName", &PadName);
      R__insp.Inspect(R__cl, R__parent, "*fConsumerInfos", &fConsumerInfos);
      R__insp.Inspect(R__cl, R__parent, "*consumerlist", &consumerlist);
      R__insp.Inspect(R__cl, R__parent, "*fConsumerListBox", &fConsumerListBox);
      R__insp.Inspect(R__cl, R__parent, "*fDisplayedList", &fDisplayedList);
      R__insp.Inspect(R__cl, R__parent, "*fDisplayedRefList", &fDisplayedRefList);
      R__insp.Inspect(R__cl, R__parent, "Running", &Running);
      R__insp.Inspect(R__cl, R__parent, "*fUpdateTimer", &fUpdateTimer);
      R__insp.Inspect(R__cl, R__parent, "*fSlideCanvasList", &fSlideCanvasList);
      R__insp.Inspect(R__cl, R__parent, "*fChButtonSlideUpdate", &fChButtonSlideUpdate);
      R__insp.Inspect(R__cl, R__parent, "SlideShowUpdate", &SlideShowUpdate);
      R__insp.Inspect(R__cl, R__parent, "*fSlideTimer", &fSlideTimer);
      R__insp.Inspect(R__cl, R__parent, "*fPrinter", &fPrinter);
      R__insp.Inspect(R__cl, R__parent, "*fPrinterCommand", &fPrinterCommand);
      R__insp.Inspect(R__cl, R__parent, "*fPrintHistoButton", &fPrintHistoButton);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_HistoDisplay(void *p) {
      delete ((::HistoDisplay*)p);
   }
   static void deleteArray_HistoDisplay(void *p) {
      delete [] ((::HistoDisplay*)p);
   }
   static void destruct_HistoDisplay(void *p) {
      typedef ::HistoDisplay current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::HistoDisplay

/********************************************************
* /home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/src/common/HistoDisplayDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableHistoDisplayDict();

extern "C" void G__set_cpp_environmentHistoDisplayDict() {
  G__add_macro("G__CINTVERSION=50160005");
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/include/HistoDisplay.hh");
  G__cpp_reset_tagtableHistoDisplayDict();
}
class G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondIHistoDisplayDictdOcc_tag {};

void* operator new(size_t size,G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondIHistoDisplayDictdOcc_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondIHistoDisplayDictdOcc_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondIHistoDisplayDictdOcc() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevHistoDisplayDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* HistoDisplay */
static int G__HistoDisplayDict_335_5_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   HistoDisplay *p=NULL;
      p = new HistoDisplay(
(const TGWindow*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_6_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((HistoDisplay*)(G__getstructoffset()))->ProcessMessage((Long_t)G__int(libp->para[0]),(Long_t)G__int(libp->para[1])
,(Long_t)G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_7_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 3:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->OpenFile((const char*)G__int(libp->para[0]),(HistoDisplay::EInputTypes)G__int(libp->para[1])
,(Option_t*)G__int(libp->para[2])));
      break;
   case 2:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->OpenFile((const char*)G__int(libp->para[0]),(HistoDisplay::EInputTypes)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->OpenFile((const char*)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_8_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->CloseFile((const char*)G__int(libp->para[0]),(HistoDisplay::EInputTypes)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->CloseFile((const char*)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_9_8(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->CloseFile((TObject*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_0_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((HistoDisplay*)(G__getstructoffset()))->CloseConnection();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_1_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->AutoOpen((const char*)G__int(libp->para[0]),(HistoDisplay::EInputTypes)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->AutoOpen((const char*)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_2_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->AutoClose((const char*)G__int(libp->para[0]),(HistoDisplay::EInputTypes)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((HistoDisplay*)(G__getstructoffset()))->AutoClose((const char*)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_3_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((HistoDisplay*)(G__getstructoffset()))->AutoOpenConsumer((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_4_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((HistoDisplay*)(G__getstructoffset()))->OpenConsumerListBox();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_5_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((HistoDisplay*)(G__getstructoffset()))->AutoReconnect();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_6_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)HistoDisplay::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_7_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)HistoDisplay::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_8_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)HistoDisplay::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_9_9(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      HistoDisplay::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_0_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const HistoDisplay*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_1_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((HistoDisplay*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_2_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((HistoDisplay*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_3_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((HistoDisplay*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_4_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)HistoDisplay::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_5_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)HistoDisplay::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_6_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)HistoDisplay::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__HistoDisplayDict_335_7_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)HistoDisplay::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__HistoDisplayDict_335_8_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   HistoDisplay *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new HistoDisplay(*(HistoDisplay*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef HistoDisplay G__THistoDisplay;
static int G__HistoDisplayDict_335_9_10(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (HistoDisplay *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (HistoDisplay *)((G__getstructoffset())+sizeof(HistoDisplay)*i);
   else  delete (HistoDisplay *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* HistoDisplay */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncHistoDisplayDict {
 public:
  G__Sizep2memfuncHistoDisplayDict() {p=&G__Sizep2memfuncHistoDisplayDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncHistoDisplayDict::*p)();
};

size_t G__get_sizep2memfuncHistoDisplayDict()
{
  G__Sizep2memfuncHistoDisplayDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceHistoDisplayDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay))) {
     HistoDisplay *G__Lderived;
     G__Lderived=(HistoDisplay*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),G__get_linked_tagnum(&G__HistoDisplayDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),G__get_linked_tagnum(&G__HistoDisplayDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),G__get_linked_tagnum(&G__HistoDisplayDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),G__get_linked_tagnum(&G__HistoDisplayDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),G__get_linked_tagnum(&G__HistoDisplayDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableHistoDisplayDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,
-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("Bool_t",103,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,
-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__HistoDisplayDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: HistoDisplayDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__HistoDisplayDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoDisplayDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: HistoDisplayDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__HistoDisplayDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__HistoDisplayDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: HistoDisplayDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* HistoDisplay */
static void G__setup_memvarHistoDisplay(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay));
   { HistoDisplay *p; p=(HistoDisplay*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGMenuBar),-1,-1,4,"fMenuBar=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fMenuBarLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fMenuBarItemLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fMenuBarHelpLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPopupMenu),-1,-1,4,"fFileMenu=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPopupMenu),-1,-1,4,"fNewCascadeMenu=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPopupMenu),-1,-1,4,"fListTreeMenu=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPopupMenu),-1,-1,4,"fSortCascadeMenu=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPopupMenu),-1,-1,4,"fConnectMenu=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPopupMenu),-1,-1,4,"fHelpMenu=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGHorizontal3DLine),-1,-1,4,"fMenuBarSeparator=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fMenuBarSeparatorLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fMainFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fMainFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,107,0,0,-1,G__defined_typename("ULong_t"),-1,4,"LightYellow=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fTitleFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fTitleFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLabel),-1,-1,4,"fTitleLabel=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fTitleLabelLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,107,0,0,-1,G__defined_typename("GContext_t"),-1,4,"fTextGC=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPictureButton),-1,-1,4,"fPicBut=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fPictLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGGroupFrame),-1,-1,4,"fFileNameFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fFileNameFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGRadioButton),-1,-1,4,"fRaButMFile=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGRadioButton),-1,-1,4,"fRaButRFile=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGRadioButton),-1,-1,4,"fRaButSocket=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGRadioButton),-1,-1,4,"fRaButSOAP=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fRaButLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLabel),-1,-1,4,"fFileNameLabel=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fFileNameLabelLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fFileOpenFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fFileOpenFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextEntry),-1,-1,4,"fFileNameTextEntry=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fFileNameTextEntryLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextBuffer),-1,-1,4,"fFileNameBuffer=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextBuffer),-1,-1,4,"fRefNameBuffer=",0,"Cavanaugh 03.04.2005");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextBuffer),-1,-1,4,"fDynRefNameBuffer=",0,"Cavanaugh 23.04.2005");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fReadFileButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fReadFileButtonLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fFileNameButtonFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fFileNameButtonFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fChooseFileButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fChooseFileButtonLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fClearFileNameButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fClearFileNameButtonLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fListTreeMainFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fListTreeMainFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fHistoListFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fRefListFrame=",0,"Cavanaugh 03.04.2005");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fHistoListFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fRefListFrameLayout=",0,"Cavanaugh 03.04.2005");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCanvas),-1,-1,4,"fTGCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fTGCanvasLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGListTree),-1,-1,4,"fHistoListTree=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGListTree),-1,-1,4,"fRefListTree=",0,"Cavanaugh 03.04.2005");
   G__memvar_setup((void*)NULL,105,0,0,-1,-1,-1,4,"REF_FLAG=",0,"Cavanaugh 03.04.2005");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fListButtonFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fListButtonFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCheckButton),-1,-1,4,"fChButtonAutoUpdate=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fChButtonAutoUpdateLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"AutoUpdate=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fFrequencyFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fFrequencyFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLabel),-1,-1,4,"fFrequencyLabel=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextEntry),-1,-1,4,"fFrequencyTextEntry=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextBuffer),-1,-1,4,"fFrequencyTextBuffer=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fControlButtonFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fControlButtonFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fButtonFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fButtonFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fButtonLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fStartHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fPauseHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fRestartHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fClearHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fStopHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGGroupFrame),-1,-1,4,"fHistoButtonGFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fHistoButtonGFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame),-1,-1,4,"fHistoButtonFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fHistoButtonFrameLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints),-1,-1,4,"fHistoButtonLayout=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fZeroHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fUnZeroHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fRefHistoButton=",0,"Cavanaugh 03.04.2005");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fContentHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGStatusBar),-1,-1,4,"fStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGListTreeItem),-1,-1,4,"fSelectedItem=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,67,0,1,-1,-1,-1,4,"PadName=",0,"Cavanaugh 21.04.2005");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TList),-1,-1,4,"fConsumerInfos=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_ConsumerList),-1,-1,4,"consumerlist=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_ConsumerListBox),-1,-1,4,"fConsumerListBox=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TList),-1,-1,4,"fDisplayedList=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TList),-1,-1,4,"fDisplayedRefList=",0,"Cavanaugh 03.04.2005");
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"Running=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplayUpdateTimer),-1,-1,4,"fUpdateTimer=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TList),-1,-1,4,"fSlideCanvasList=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCheckButton),-1,-1,4,"fChButtonSlideUpdate=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-1,4,"SlideShowUpdate=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplaySlideTimer),-1,-1,4,"fSlideTimer=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,67,0,0,-1,-1,-1,4,"fPrinter=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,67,0,0,-1,-1,-1,4,"fPrinterCommand=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton),-1,-1,4,"fPrintHistoButton=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes),-1,-2,1,"kTMapFile=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes),-1,-2,1,"kTFile=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes),-1,-2,1,"kTSocket=2",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes),-1,-2,1,"kTSOAP=3",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__HistoDisplayDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarHistoDisplayDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncHistoDisplay(void) {
   /* HistoDisplay */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay));
   G__memfunc_setup("MakeMenuBar",1064,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseMenuBar",1184,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeTitleFrame",1387,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"C - - 10 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseTitleFrame",1507,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeInputFrame",1401,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseInputFrame",1521,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeTGListTreeFrame",1840,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeTGRefListTreeFrame",2125,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("CloseTGListTreeFrame",1960,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeStatusBar",1303,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseStatusBar",1423,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("FileDialogWindow",1608,(G__InterfaceMethod)NULL,67,-1,-1,0,0,1,4,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("FileNameClear",1256,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MessageBox",1006,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"C - - 10 - msg",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddToTree",860,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"C - - 10 - objname U 'TObject' - 0 - inputobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeTGListTree",1349,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"u 'TString' - 11 - - U 'TObject' - 0 - - "
"C - - 10 0 tip",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RemoveTGListTree",1589,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SortTGListTree",1391,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DelTreeItemsOfInput",1900,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TObject' - 0 - inputobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddTreeItemsOfInput",1888,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TObject' - 0 - inputobj g - 'Bool_t' 0 kTRUE newlyOpened",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RefreshTreeItem",1518,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeleteEmptyFolders",1841,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakePathName",1164,(G__InterfaceMethod)NULL,117,G__get_linked_tagnum(&G__HistoDisplayDictLN_TString),-1,0,2,1,4,0,
"C - - 10 - dir C - - 10 - objname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddTreeItems",1179,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"U 'TConsumerInfo' - 0 - info U 'TObject' - 0 - inputobj "
"g - 'Bool_t' 0 kTRUE newlyOpened",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SubtractTreeItems",1754,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TConsumerInfo' - 0 - info",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeleteTreeItem",1394,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddRefTreeItemsOfInput",2173,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TObject' - 0 - inputobj g - 'Bool_t' 0 kTRUE newlyOpened","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("MakeRefHistoList",1598,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TObject' - 0 - inpuobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddRefTreeItems",1464,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"U 'TConsumerInfo' - 0 - info U 'TObject' - 0 - inputobj "
"g - 'Bool_t' 0 kTRUE newlyOpened","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("AddToRefTree",1145,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"C - - 10 - objname U 'TObject' - 0 - inputobj","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("MakeTGRefListTree",1634,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"u 'TString' - 11 - - U 'TObject' - 0 - - "
"C - - 10 0 tip","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("SubtractRefTreeItems",2039,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TConsumerInfo' - 0 - info","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("DeleteEmptyRefFolders",2126,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("DisplayRefHisto",1530,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TVirtualPad' - 0 - currentPad","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("UpdateRefHistoList",1827,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_CObject),-1,0,3,1,4,0,
"C - - 10 - objPath C - - 10 - objName "
"U 'TObject' - 10 - inputobj","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("AddRefPadHistosToHistoList",2587,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TPad' - 0 - pad","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("GetCObjFromRefListItem",2138,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_CObject),-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item","Cavanaugh 03.04.2005",(void*)NULL,0);
   G__memfunc_setup("MakeConsumerInfo",1622,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TConsumerInfo),-1,0,1,1,4,0,"U 'TObject' - 0 - inputobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeConsumerInfo",1622,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TConsumerInfo),-1,0,2,1,4,0,
"C - - 10 - consumername C - - 10 - filename",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DelTreeItemsOfInfo",1768,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TConsumerInfo' - 0 - info",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetConsumerInfoFromList",2344,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TConsumerInfo),-1,0,1,1,4,0,"C - - 10 - consumer",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddConsumerInfo",1505,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TConsumerInfo),-1,0,1,1,4,0,"U 'TConsumerInfo' - 0 - info",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DelConsumerInfo",1517,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TConsumerInfo' - 0 - info",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UpdateHistoList",1542,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_CObject),-1,0,3,1,4,0,
"C - - 10 - objPath C - - 10 - objName "
"U 'TObject' - 10 - inputobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetNewObj",869,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject),-1,0,3,1,4,0,
"C - - 10 - objPath C - - 10 - objName "
"U 'TObject' - 10 - inputobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetCObjFromListItem",1853,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_CObject),-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeHistoList",1313,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TObject' - 0 - inpuobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeHistoListM",1390,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TMapFile' - 0 - MFile",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeHistoListR",1395,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TFile' - 0 - RFile",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MakeHistoListS",1396,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TSocket' - 0 - sock",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawHisto",917,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TObject' - 0 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawHisto",917,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TList' - 0 - list",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawTH1",603,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"U 'TH1' - 0 - histo C - 'Option_t' 10 - option "
"U 'TVirtualPad' - 0 - backpad",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawTPad",759,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TPad' - 0 - pad1 U 'TVirtualPad' - 0 - pad2",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UpdateTimerOn",1313,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UpdateCanvas",1215,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TVirtualPad' - 0 0 currentpad",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UpdatePad",888,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TVirtualPad' - 0 - pad",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawUpdatedPad",1386,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TVirtualPad' - 0 - currentPad",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ReplacePad",977,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TVirtualPad' - 0 - newpad U 'TVirtualPad' - 0 - oldpad",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ReplaceHisto",1219,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TH1' - 0 - histo U 'TH1' - 0 - histoOld",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ReplaceHistoFunc",1615,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TH1' - 0 - histo U 'TH1' - 0 - histoOld",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddPadHistosToHistoList",2302,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TPad' - 0 - pad",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AddSubtractHisto",1624,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TVirtualPad' - 0 - currentPad i - - 0 - option",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClearCurrentPad",1503,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RecursivePadClear",1716,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TVirtualPad' - 0 - pad C - 'Option_t' 10 \"\" option",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CycleSlides",1108,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"U 'TGListTreeItem' - 0 - item U 'TVirtualPad' - 0 - currentpad "
"U 'TGListTreeItem' - 0 - displayingitem",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SlideTimerOn",1199,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("StartSlides",1138,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TGListTreeItem' - 0 - item",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("PopUpSlides",1112,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"U 'TGListTreeItem' - 0 - item C - - 10 - canvasname "
"C - - 10 - canvastitle",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SearchWarningFolder",1928,(G__InterfaceMethod)NULL,121,-1,-1,0,3,1,4,0,
"U 'TGListTreeItem' - 0 - item U 'TObject' - 0 - socket "
"g - 'Bool_t' 1 - FoundWarningFolder",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SearchWarningFolder",1928,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TConsumerInfo' - 0 - info U 'TObject' - 0 - socket",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ContentHisto",1250,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TH1F),-1,0,1,1,4,0,"U 'TH1' - 0 - histo",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawOnTheCanvas",1480,(G__InterfaceMethod)NULL,121,-1,-1,0,5,1,4,0,
"C - - 10 - canvasname C - - 10 - canvastitle "
"i - - 0 - padx i - - 0 - pady "
"U 'TObject' - 0 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawContentHisto",1648,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TH1' - 0 - histo",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HistoInPad",979,(G__InterfaceMethod)NULL,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TH1),-1,0,2,1,4,0,
"U 'TVirtualPad' - 0 - pad i - 'Int_t' 1 - counthisto",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("PrintCanvas",1129,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TPad' - 0 - canvas",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("OpenDefaultCanvas",1715,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ChangeCanvasNameTitle",2085,(G__InterfaceMethod)NULL,121,-1,-1,0,1,1,4,0,"U 'TCanvas' - 0 - canvas",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DuplicateCanvasSize",1938,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"U 'TCanvas' - 0 - guicanvas U 'TCanvas' - 0 - consumercanvas",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ResetObjects",1229,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MenuConnectStatus",1763,(G__InterfaceMethod)NULL,121,-1,-1,0,0,1,4,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MenuHelp",798,(G__InterfaceMethod)NULL,121,-1,-1,0,2,1,4,0,
"C - - 0 - s C - - 10 - helpText",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HostPortFromID",1380,(G__InterfaceMethod)NULL,67,-1,-1,0,1,1,4,8,"h - 'UInt_t' 10 - id",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("HistoDisplay",1245,G__HistoDisplayDict_335_5_8,105,G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),-1,0,3,1,1,0,
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ProcessMessage",1444,G__HistoDisplayDict_335_6_8,103,-1,G__defined_typename("Bool_t"),0,3,1,1,0,
"l - 'Long_t' 0 - msg l - 'Long_t' 0 - parm1 "
"l - 'Long_t' 0 - parm2",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("OpenFile",786,G__HistoDisplayDict_335_7_8,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject),-1,0,3,1,1,0,
"C - - 10 - filename i 'HistoDisplay::EInputTypes' - 0 kTFile inputtype "
"C - 'Option_t' 10 \"READ\" option",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseFile",886,G__HistoDisplayDict_335_8_8,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject),-1,0,2,1,1,0,
"C - - 10 - filename i 'HistoDisplay::EInputTypes' - 0 kTFile inputtype",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseFile",886,G__HistoDisplayDict_335_9_8,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject),-1,0,1,1,1,0,"U 'TObject' - 0 - inputobj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CloseConnection",1542,G__HistoDisplayDict_335_0_9,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AutoOpen",811,G__HistoDisplayDict_335_1_9,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject),-1,0,2,1,1,0,
"C - - 10 - servername i 'HistoDisplay::EInputTypes' - 0 kTSocket inputtype",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AutoClose",911,G__HistoDisplayDict_335_2_9,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject),-1,0,2,1,1,0,
"C - - 10 - filename i 'HistoDisplay::EInputTypes' - 0 kTSocket inputtype",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AutoOpenConsumer",1655,G__HistoDisplayDict_335_3_9,121,-1,-1,0,1,1,1,0,"C - - 10 - consumername",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("OpenConsumerListBox",1955,G__HistoDisplayDict_335_4_9,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("AutoReconnect",1338,G__HistoDisplayDict_335_5_9,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__HistoDisplayDict_335_6_9,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&HistoDisplay::Class),0);
   G__memfunc_setup("Class_Name",982,G__HistoDisplayDict_335_7_9,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&HistoDisplay::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__HistoDisplayDict_335_8_9,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&HistoDisplay::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__HistoDisplayDict_335_9_9,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&HistoDisplay::Dictionary),0);
   G__memfunc_setup("IsA",253,G__HistoDisplayDict_335_0_10,85,G__get_linked_tagnum(&G__HistoDisplayDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__HistoDisplayDict_335_1_10,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__HistoDisplayDict_335_2_10,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__HistoDisplayDict_335_3_10,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__HistoDisplayDict_335_4_10,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&HistoDisplay::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__HistoDisplayDict_335_5_10,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&HistoDisplay::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__HistoDisplayDict_335_6_10,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&HistoDisplay::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__HistoDisplayDict_335_7_10,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&HistoDisplay::DeclFileLine),0);
   // automatic copy constructor
   G__memfunc_setup("HistoDisplay",1245,G__HistoDisplayDict_335_8_10,(int)('i'),G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),-1,0,1,1,1,0,"u 'HistoDisplay' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~HistoDisplay",1371,G__HistoDisplayDict_335_9_10,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncHistoDisplayDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalHistoDisplayDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcHistoDisplayDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__HistoDisplayDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TVirtualPad = { "TVirtualPad" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGLayoutHints = { "TGLayoutHints" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGGroupFrame = { "TGGroupFrame" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGMenuBar = { "TGMenuBar" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGPopupMenu = { "TGPopupMenu" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGHorizontal3DLine = { "TGHorizontal3DLine" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGPictureButton = { "TGPictureButton" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGTextBuffer = { "TGTextBuffer" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGListTree = { "TGListTree" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGListTreeItem = { "TGListTreeItem" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGCanvas = { "TGCanvas" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TPad = { "TPad" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TMapFile = { "TMapFile" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TSocket = { "TSocket" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_TConsumerInfo = { "TConsumerInfo" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_ConsumerList = { "ConsumerList" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_ConsumerListBox = { "ConsumerListBox" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_CObject = { "CObject" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_HistoDisplayUpdateTimer = { "HistoDisplayUpdateTimer" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_HistoDisplaySlideTimer = { "HistoDisplaySlideTimer" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_HistoDisplay = { "HistoDisplay" , 99 , -1 };
G__linked_taginfo G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes = { "HistoDisplay::EInputTypes" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableHistoDisplayDict() {
  G__HistoDisplayDictLN_TClass.tagnum = -1 ;
  G__HistoDisplayDictLN_TBuffer.tagnum = -1 ;
  G__HistoDisplayDictLN_TMemberInspector.tagnum = -1 ;
  G__HistoDisplayDictLN_TObject.tagnum = -1 ;
  G__HistoDisplayDictLN_TList.tagnum = -1 ;
  G__HistoDisplayDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__HistoDisplayDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__HistoDisplayDictLN_TString.tagnum = -1 ;
  G__HistoDisplayDictLN_TFile.tagnum = -1 ;
  G__HistoDisplayDictLN_TVirtualPad.tagnum = -1 ;
  G__HistoDisplayDictLN_TGObject.tagnum = -1 ;
  G__HistoDisplayDictLN_TGWindow.tagnum = -1 ;
  G__HistoDisplayDictLN_TQObject.tagnum = -1 ;
  G__HistoDisplayDictLN_TGFrame.tagnum = -1 ;
  G__HistoDisplayDictLN_TGCompositeFrame.tagnum = -1 ;
  G__HistoDisplayDictLN_TGLayoutHints.tagnum = -1 ;
  G__HistoDisplayDictLN_TGMainFrame.tagnum = -1 ;
  G__HistoDisplayDictLN_TGGroupFrame.tagnum = -1 ;
  G__HistoDisplayDictLN_TGMenuBar.tagnum = -1 ;
  G__HistoDisplayDictLN_TGPopupMenu.tagnum = -1 ;
  G__HistoDisplayDictLN_TGHorizontal3DLine.tagnum = -1 ;
  G__HistoDisplayDictLN_TGPictureButton.tagnum = -1 ;
  G__HistoDisplayDictLN_TGLabel.tagnum = -1 ;
  G__HistoDisplayDictLN_TGTextEntry.tagnum = -1 ;
  G__HistoDisplayDictLN_TGTextBuffer.tagnum = -1 ;
  G__HistoDisplayDictLN_TGTextButton.tagnum = -1 ;
  G__HistoDisplayDictLN_TGCheckButton.tagnum = -1 ;
  G__HistoDisplayDictLN_TGRadioButton.tagnum = -1 ;
  G__HistoDisplayDictLN_TGListTree.tagnum = -1 ;
  G__HistoDisplayDictLN_TGListTreeItem.tagnum = -1 ;
  G__HistoDisplayDictLN_TGCanvas.tagnum = -1 ;
  G__HistoDisplayDictLN_TH1.tagnum = -1 ;
  G__HistoDisplayDictLN_TH1F.tagnum = -1 ;
  G__HistoDisplayDictLN_TPad.tagnum = -1 ;
  G__HistoDisplayDictLN_TCanvas.tagnum = -1 ;
  G__HistoDisplayDictLN_TMapFile.tagnum = -1 ;
  G__HistoDisplayDictLN_TSocket.tagnum = -1 ;
  G__HistoDisplayDictLN_TGStatusBar.tagnum = -1 ;
  G__HistoDisplayDictLN_TConsumerInfo.tagnum = -1 ;
  G__HistoDisplayDictLN_ConsumerList.tagnum = -1 ;
  G__HistoDisplayDictLN_ConsumerListBox.tagnum = -1 ;
  G__HistoDisplayDictLN_CObject.tagnum = -1 ;
  G__HistoDisplayDictLN_HistoDisplayUpdateTimer.tagnum = -1 ;
  G__HistoDisplayDictLN_HistoDisplaySlideTimer.tagnum = -1 ;
  G__HistoDisplayDictLN_HistoDisplay.tagnum = -1 ;
  G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableHistoDisplayDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TClass);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TBuffer);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TObject);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TList);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TString);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TFile);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TVirtualPad);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGObject);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGWindow);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TQObject);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGFrame);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCompositeFrame);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLayoutHints);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGMainFrame);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGGroupFrame);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGMenuBar);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPopupMenu);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGHorizontal3DLine);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGPictureButton);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGLabel);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextEntry);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextBuffer);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGTextButton);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCheckButton);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGRadioButton);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGListTree);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGListTreeItem);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGCanvas);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TH1);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TH1F);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TPad);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TCanvas);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TMapFile);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TSocket);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TGStatusBar);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_TConsumerInfo);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_ConsumerList);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_ConsumerListBox);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_CObject);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplayUpdateTimer);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplaySlideTimer);
   G__tagtable_setup(G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplay),sizeof(HistoDisplay),-1,62464,(char*)NULL,G__setup_memvarHistoDisplay,G__setup_memfuncHistoDisplay);
   G__get_linked_tagnum(&G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes);
}
extern "C" void G__cpp_setupHistoDisplayDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupHistoDisplayDict()");
  G__set_cpp_environmentHistoDisplayDict();
  G__cpp_setup_tagtableHistoDisplayDict();

  G__cpp_setup_inheritanceHistoDisplayDict();

  G__cpp_setup_typetableHistoDisplayDict();

  G__cpp_setup_memvarHistoDisplayDict();

  G__cpp_setup_memfuncHistoDisplayDict();
  G__cpp_setup_globalHistoDisplayDict();
  G__cpp_setup_funcHistoDisplayDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncHistoDisplayDict();
  return;
}
class G__cpp_setup_initHistoDisplayDict {
  public:
    G__cpp_setup_initHistoDisplayDict() { G__add_setup_func("HistoDisplayDict",(G__incsetup)(&G__cpp_setupHistoDisplayDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initHistoDisplayDict() { G__remove_setup_func("HistoDisplayDict"); }
};
G__cpp_setup_initHistoDisplayDict G__cpp_setup_initializerHistoDisplayDict;

