//
// File generated by /opt/cern/root/bin/rootcint at Tue Feb 14 19:12:41 2006.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "TConsumerInfoDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void TConsumerInfo_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_TConsumerInfo(void *p = 0);
   static void *newArray_TConsumerInfo(Long_t size);
   static void delete_TConsumerInfo(void *p);
   static void deleteArray_TConsumerInfo(void *p);
   static void destruct_TConsumerInfo(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const ::TConsumerInfo*)
   {
      ::TConsumerInfo *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TConsumerInfo >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TConsumerInfo", ::TConsumerInfo::Class_Version(), "/home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/include/TConsumerInfo.hh", 28,
                  typeid(::TConsumerInfo), DefineBehavior(ptr, ptr),
                  &::TConsumerInfo::Dictionary, isa_proxy, 1,
                  sizeof(::TConsumerInfo) );
      instance.SetNew(&new_TConsumerInfo);
      instance.SetNewArray(&newArray_TConsumerInfo);
      instance.SetDelete(&delete_TConsumerInfo);
      instance.SetDeleteArray(&deleteArray_TConsumerInfo);
      instance.SetDestructor(&destruct_TConsumerInfo);
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const ::TConsumerInfo*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *TConsumerInfo::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TConsumerInfo::Class_Name()
{
   return "TConsumerInfo";
}

//______________________________________________________________________________
const char *TConsumerInfo::ImplFileName()
{
   return ::ROOT::GenerateInitInstance((const ::TConsumerInfo*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TConsumerInfo::ImplFileLine()
{
   return ::ROOT::GenerateInitInstance((const ::TConsumerInfo*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TConsumerInfo::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstance((const ::TConsumerInfo*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TConsumerInfo::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstance((const ::TConsumerInfo*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TConsumerInfo::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TConsumerInfo.

      TClass *R__cl = ::TConsumerInfo::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "_inputname", &_inputname);
      _inputname.ShowMembers(R__insp, strcat(R__parent,"_inputname.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*_list", &_list);
      R__insp.Inspect(R__cl, R__parent, "_modified", &_modified);
      R__insp.Inspect(R__cl, R__parent, "_runnumber", &_runnumber);
      R__insp.Inspect(R__cl, R__parent, "_nevents", &_nevents);
      R__insp.Inspect(R__cl, R__parent, "_estimatedsize", &_estimatedsize);
      TNamed::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TConsumerInfo(void *p) {
      return  p ? new(p) ::TConsumerInfo : new ::TConsumerInfo;
   }
   static void *newArray_TConsumerInfo(Long_t size) {
      return new ::TConsumerInfo[size];
   }
   // Wrapper around operator delete
   static void delete_TConsumerInfo(void *p) {
      delete ((::TConsumerInfo*)p);
   }
   static void deleteArray_TConsumerInfo(void *p) {
      delete [] ((::TConsumerInfo*)p);
   }
   static void destruct_TConsumerInfo(void *p) {
      typedef ::TConsumerInfo current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TConsumerInfo

/********************************************************
* /home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/src/common/TConsumerInfoDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTConsumerInfoDict();

extern "C" void G__set_cpp_environmentTConsumerInfoDict() {
  G__add_macro("G__CINTVERSION=50160005");
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/dqm/TriDAS/emu/emuDQM/EmuROOTDisplayServer/include/TConsumerInfo.hh");
  G__cpp_reset_tagtableTConsumerInfoDict();
}
class G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondITConsumerInfoDictdOcc_tag {};

void* operator new(size_t size,G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondITConsumerInfoDictdOcc_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondITConsumerInfoDictdOcc_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_dIhomedIdqmdITriDASdIemudIemuDQMdIEmuROOTDisplayServerdIsrcdIcommondITConsumerInfoDictdOcc() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevTConsumerInfoDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TConsumerInfo */
static int G__TConsumerInfoDict_418_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TConsumerInfo *p=NULL;
   switch(libp->paran) {
   case 2:
      p = new TConsumerInfo((const char *const)G__int(libp->para[0]),(int)G__int(libp->para[1]));
      break;
   case 1:
      p = new TConsumerInfo((const char *const)G__int(libp->para[0]));
      break;
   case 0:
   if(G__getaryconstruct()) p=new TConsumerInfo[G__getaryconstruct()];
   else                    p=new TConsumerInfo;
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((const TConsumerInfo*)(G__getstructoffset()))->consumername());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->clear();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setConsumername((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 4:
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->addObject(*(TString*)libp->para[0].ref,*(TString*)libp->para[1].ref
,(int)G__int(libp->para[2]),(TObject*)G__int(libp->para[3]));
      break;
   case 3:
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->addObject(*(TString*)libp->para[0].ref,*(TString*)libp->para[1].ref
,(int)G__int(libp->para[2]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->removeObject(*(TString*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->removeObject(*(TString*)libp->para[0].ref,*(TString*)libp->para[1].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->removeObject((TObject*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->removeObject((TObject*)G__int(libp->para[0]),*(TString*)libp->para[1].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->emptyWarningFolder();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setPath(*(TString*)libp->para[0].ref,*(TString*)libp->para[1].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setPath(*(TString*)libp->para[0].ref,*(TString*)libp->para[1].ref
,*(TString*)libp->para[2].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setStatus(*(TString*)libp->para[0].ref,(int)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setAddress(*(TString*)libp->para[0].ref,(TObject*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
const         TString *pobj,xobj=((const TConsumerInfo*)(G__getstructoffset()))->getPath(*(TString*)libp->para[0].ref);
        pobj=new TString(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const TConsumerInfo*)(G__getstructoffset()))->getStatus(*(TString*)libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TConsumerInfo*)(G__getstructoffset()))->getAddress(*(TString*)libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
const         TString *pobj,xobj=((const TConsumerInfo*)(G__getstructoffset()))->getToolTip(*(TString*)libp->para[0].ref);
        pobj=new TString(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((TConsumerInfo*)(G__getstructoffset()))->hasEntry(*(TString*)libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setNevents((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setRunNumber((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const TConsumerInfo*)(G__getstructoffset()))->runnumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const TConsumerInfo*)(G__getstructoffset()))->nevents());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((const TConsumerInfo*)(G__getstructoffset()))->isModified());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setModified((bool)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->setInputName(*(TString*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        const TString& obj=((const TConsumerInfo*)(G__getstructoffset()))->getInputName();
         result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,108,(long)((const TConsumerInfo*)(G__getstructoffset()))->estimatedSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TConsumerInfo*)(G__getstructoffset()))->list());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->updateList((TList*)G__int(libp->para[0]),(TSocket*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
      G__setnull(result7);
      ((const TConsumerInfo*)(G__getstructoffset()))->print(*(ostream*)libp->para[0].ref);
      break;
   case 0:
      G__setnull(result7);
      ((const TConsumerInfo*)(G__getstructoffset()))->print();
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TConsumerInfo::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TConsumerInfo::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TConsumerInfo::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TConsumerInfo::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TConsumerInfo*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_7_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_8_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_9_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TConsumerInfo*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_0_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TConsumerInfo::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_1_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TConsumerInfo::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_2_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TConsumerInfo::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TConsumerInfoDict_418_3_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TConsumerInfo::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TConsumerInfoDict_418_4_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   TConsumerInfo *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new TConsumerInfo(*(TConsumerInfo*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TConsumerInfo G__TTConsumerInfo;
static int G__TConsumerInfoDict_418_5_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TConsumerInfo *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TConsumerInfo *)((G__getstructoffset())+sizeof(TConsumerInfo)*i);
   else  delete (TConsumerInfo *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TConsumerInfoDict_418_6_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TConsumerInfo *dest = (TConsumerInfo*)(G__getstructoffset());
   *dest = (*(TConsumerInfo*)libp->para[0].ref);
   const TConsumerInfo& obj = *dest;
   result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TConsumerInfo */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTConsumerInfoDict {
 public:
  G__Sizep2memfuncTConsumerInfoDict() {p=&G__Sizep2memfuncTConsumerInfoDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTConsumerInfoDict::*p)();
};

size_t G__get_sizep2memfuncTConsumerInfoDict()
{
  G__Sizep2memfuncTConsumerInfoDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTConsumerInfoDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo))) {
     TConsumerInfo *G__Lderived;
     G__Lderived=(TConsumerInfo*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo),G__get_linked_tagnum(&G__TConsumerInfoDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo),G__get_linked_tagnum(&G__TConsumerInfoDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTConsumerInfoDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__TConsumerInfoDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TConsumerInfoDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TConsumerInfoDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TConsumerInfoDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TConsumerInfoDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TConsumerInfoDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TConsumerInfoDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TConsumerInfoDict.cc,v 1.1 2006/02/16 00:05:14 barvic Exp $",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TConsumerInfo */
static void G__setup_memvarTConsumerInfo(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo));
   { TConsumerInfo *p; p=(TConsumerInfo*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfocLcLdA),-1,-2,1,"Okay=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfocLcLdA),-1,-2,1,"Warning=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfocLcLdA),-1,-2,1,"Error=2",0,(char*)NULL);
   G__memvar_setup((void*)NULL,117,0,0,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TString),-1,-1,4,"_inputname=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TList),-1,-1,4,"_list=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,103,0,0,-1,-1,-1,4,"_modified=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"_runnumber=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"_nevents=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,108,0,0,-1,-1,-1,4,"_estimatedsize=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTConsumerInfoDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTConsumerInfo(void) {
   /* TConsumerInfo */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo));
   G__memfunc_setup("TConsumerInfo",1324,G__TConsumerInfoDict_418_1_0,105,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo),-1,0,2,1,1,0,
"C - - 50 \"\" consumername i - - 0 0 runnumber",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("consumername",1293,G__TConsumerInfoDict_418_2_0,67,-1,-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("clear",519,G__TConsumerInfoDict_418_3_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setConsumername",1593,G__TConsumerInfoDict_418_4_0,121,-1,-1,0,1,1,1,0,"C - - 10 - name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addObject",896,G__TConsumerInfoDict_418_5_0,121,-1,-1,0,4,1,1,0,
"u 'TString' - 11 - name u 'TString' - 11 - path "
"i - - 0 - status U 'TObject' - 0 NULL obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("removeObject",1253,G__TConsumerInfoDict_418_6_0,121,-1,-1,0,1,1,1,0,"u 'TString' - 11 - name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("removeObject",1253,G__TConsumerInfoDict_418_7_0,121,-1,-1,0,2,1,1,0,
"u 'TString' - 11 - name u 'TString' - 11 - path",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("removeObject",1253,G__TConsumerInfoDict_418_8_0,121,-1,-1,0,1,1,1,0,"U 'TObject' - 0 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("removeObject",1253,G__TConsumerInfoDict_418_9_0,121,-1,-1,0,2,1,1,0,
"U 'TObject' - 0 - obj u 'TString' - 11 - path",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("emptyWarningFolder",1889,G__TConsumerInfoDict_418_0_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setPath",729,G__TConsumerInfoDict_418_1_1,121,-1,-1,0,2,1,1,0,
"u 'TString' - 11 - name u 'TString' - 11 - path",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setPath",729,G__TConsumerInfoDict_418_2_1,121,-1,-1,0,3,1,1,0,
"u 'TString' - 11 - name u 'TString' - 11 - oldpath "
"u 'TString' - 11 - newpath",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setStatus",976,G__TConsumerInfoDict_418_3_1,121,-1,-1,0,2,1,1,0,
"u 'TString' - 11 - name i - - 0 - status",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setAddress",1042,G__TConsumerInfoDict_418_4_1,121,-1,-1,0,2,1,1,0,
"u 'TString' - 11 - name U 'TObject' - 0 - obj",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPath",717,G__TConsumerInfoDict_418_5_1,117,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TString),-1,0,1,1,1,8,"u 'TString' - 11 - name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getStatus",964,G__TConsumerInfoDict_418_6_1,105,-1,G__defined_typename("Int_t"),0,1,1,1,8,"u 'TString' - 11 - name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getAddress",1030,G__TConsumerInfoDict_418_7_1,85,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TObject),-1,0,1,1,1,0,"u 'TString' - 11 - name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getToolTip",1035,G__TConsumerInfoDict_418_8_1,117,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TString),-1,0,1,1,1,8,"u 'TString' - 11 - name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("hasEntry",846,G__TConsumerInfoDict_418_9_1,103,-1,-1,0,1,1,1,0,"u 'TString' - 11 - name",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setNevents",1071,G__TConsumerInfoDict_418_0_2,121,-1,-1,0,1,1,1,0,"i - - 0 - nevents",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setRunNumber",1258,G__TConsumerInfoDict_418_1_2,121,-1,-1,0,1,1,1,0,"i - - 0 - number",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("runnumber",990,G__TConsumerInfoDict_418_2_2,105,-1,-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("nevents",771,G__TConsumerInfoDict_418_3_2,105,-1,-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("isModified",1021,G__TConsumerInfoDict_418_4_2,103,-1,-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setModified",1133,G__TConsumerInfoDict_418_5_2,121,-1,-1,0,1,1,1,0,"g - - 0 - modified",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setInputName",1245,G__TConsumerInfoDict_418_6_2,121,-1,-1,0,1,1,1,0,"u 'TString' - 11 - inputname",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getInputName",1233,G__TConsumerInfoDict_418_7_2,117,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TString),-1,1,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("estimatedSize",1371,G__TConsumerInfoDict_418_8_2,108,-1,-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("list",444,G__TConsumerInfoDict_418_9_2,85,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TList),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("updateList",1055,G__TConsumerInfoDict_418_0_3,121,-1,-1,0,2,1,1,0,
"U 'TList' - 0 - list U 'TSocket' - 0 - sock","note: only for the GUI",(void*)NULL,0);
   G__memfunc_setup("print",557,G__TConsumerInfoDict_418_1_3,121,-1,-1,0,1,1,1,8,"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 std::cout output",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__TConsumerInfoDict_418_2_3,85,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&TConsumerInfo::Class),0);
   G__memfunc_setup("Class_Name",982,G__TConsumerInfoDict_418_3_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TConsumerInfo::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__TConsumerInfoDict_418_4_3,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&TConsumerInfo::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__TConsumerInfoDict_418_5_3,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&TConsumerInfo::Dictionary),0);
   G__memfunc_setup("IsA",253,G__TConsumerInfoDict_418_6_3,85,G__get_linked_tagnum(&G__TConsumerInfoDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__TConsumerInfoDict_418_7_3,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__TConsumerInfoDict_418_8_3,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TConsumerInfoDict_418_9_3,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__TConsumerInfoDict_418_0_4,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TConsumerInfo::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__TConsumerInfoDict_418_1_4,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TConsumerInfo::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__TConsumerInfoDict_418_2_4,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TConsumerInfo::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__TConsumerInfoDict_418_3_4,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TConsumerInfo::DeclFileLine),0);
   // automatic copy constructor
   G__memfunc_setup("TConsumerInfo",1324,G__TConsumerInfoDict_418_4_4,(int)('i'),G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo),-1,0,1,1,1,0,"u 'TConsumerInfo' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~TConsumerInfo",1450,G__TConsumerInfoDict_418_5_4,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic assignment operator
   G__memfunc_setup("operator=",937,G__TConsumerInfoDict_418_6_4,(int)('u'),G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo),-1,1,1,1,1,0,"u 'TConsumerInfo' - 11 - -",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTConsumerInfoDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTConsumerInfoDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTConsumerInfoDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TConsumerInfoDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TSocket = { "TSocket" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TConsumerInfo = { "TConsumerInfo" , 99 , -1 };
G__linked_taginfo G__TConsumerInfoDictLN_TConsumerInfocLcLdA = { "TConsumerInfo::$" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTConsumerInfoDict() {
  G__TConsumerInfoDictLN_TClass.tagnum = -1 ;
  G__TConsumerInfoDictLN_TBuffer.tagnum = -1 ;
  G__TConsumerInfoDictLN_TMemberInspector.tagnum = -1 ;
  G__TConsumerInfoDictLN_TObject.tagnum = -1 ;
  G__TConsumerInfoDictLN_TNamed.tagnum = -1 ;
  G__TConsumerInfoDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__TConsumerInfoDictLN_TList.tagnum = -1 ;
  G__TConsumerInfoDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__TConsumerInfoDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TConsumerInfoDictLN_TString.tagnum = -1 ;
  G__TConsumerInfoDictLN_TSocket.tagnum = -1 ;
  G__TConsumerInfoDictLN_TConsumerInfo.tagnum = -1 ;
  G__TConsumerInfoDictLN_TConsumerInfocLcLdA.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTConsumerInfoDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TClass);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TBuffer);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TObject);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TNamed);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TList);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TString);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TSocket);
   G__tagtable_setup(G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfo),sizeof(TConsumerInfo),-1,128256,(char*)NULL,G__setup_memvarTConsumerInfo,G__setup_memfuncTConsumerInfo);
   G__get_linked_tagnum(&G__TConsumerInfoDictLN_TConsumerInfocLcLdA);
}
extern "C" void G__cpp_setupTConsumerInfoDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTConsumerInfoDict()");
  G__set_cpp_environmentTConsumerInfoDict();
  G__cpp_setup_tagtableTConsumerInfoDict();

  G__cpp_setup_inheritanceTConsumerInfoDict();

  G__cpp_setup_typetableTConsumerInfoDict();

  G__cpp_setup_memvarTConsumerInfoDict();

  G__cpp_setup_memfuncTConsumerInfoDict();
  G__cpp_setup_globalTConsumerInfoDict();
  G__cpp_setup_funcTConsumerInfoDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTConsumerInfoDict();
  return;
}
class G__cpp_setup_initTConsumerInfoDict {
  public:
    G__cpp_setup_initTConsumerInfoDict() { G__add_setup_func("TConsumerInfoDict",(G__incsetup)(&G__cpp_setupTConsumerInfoDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTConsumerInfoDict() { G__remove_setup_func("TConsumerInfoDict"); }
};
G__cpp_setup_initTConsumerInfoDict G__cpp_setup_initializerTConsumerInfoDict;

