// PERIPH_TABLE
enum {
  BX_ORBIT_loc, CCB_MODE_loc, CCB_SLOT_loc, CCB_VERSION_loc,
  PEIRPH_CONFIG_NUMBER_loc, PERIPH_CONFIG_PERIOD_loc, PERIPH_CONFIG_VERSION_loc, 
  PERIPH_CRATE_ID_loc, CRATE_LABEL_loc, CCB_L1ADELAY_loc, MPC_BOARDID_loc,
  MPC_SLOT_loc, PERIPH_KEY_loc, PORT_loc, SERIALIZERMODE_loc,
  SPS25NS_loc, TRANSPARENTMODE_loc,TTCMODE_loc,
  TTCRXCOARSEDELAY_loc,TTCRXID_loc,VMEADDRESS_loc
} ;

//CSC_TABLE
enum {
  CSC_CONFIG_NUMBER_loc, CSC_CONFIG_PERIOD_loc, CSC_CONFIG_VERSION_loc,
  CSC_CSCID_loc, CSC_KEY_loc, CSC_LABEL_loc, CSC_PRODUCTION_ID_loc,
  CSC_PERIPH_KEY_loc
};

//TMB_TABLE
enum {
  ALCT_MATCH_WINDOW_SIZE_loc, ALCT_RX_CLOCK_DELAY_loc, ALCT_TX_CLOCK_DELAY_loc,
  ALCT_VPF_DELAY_loc, CFEB0_DELAY_loc, CFEB1_DELAY_loc, CFEB2_DELAY_loc,
  CFEB3_DELAY_loc, CFEB4_DELAY_loc, TMB_CSCID_loc, TMB_CSC_KEY_loc, DMB_TX_DELAY_loc,
  DS_PRETRIG_THRESH_loc, FIFO_PRETRIG_loc, FIFO_TBINS_loc, HS_PRETRIG_THRESH_loc,
  TMB_L1ADELAY_loc, L1A_WINDOW_SIZE_loc, MIN_HITS_PATTERN_loc, MPC_DELAY_loc, MPC_TX_DELAY_loc,
  RAT_TMB_DELAY_loc, REQUEST_L1A_loc, RPC0_RAT_DELAY_loc, RPC_BXN_OFFSET_loc,
  SHIFT_RPC_loc, TMB_KEY_loc, TMB_SLOT_loc, TMB_VERSION_loc, TRGMODE_loc
};

//DMB_TABLE
enum {
  ALCT_DAV_DELAY_loc, CABLE_DELAY_loc, CALIBRATION_L1A_DELAY_loc,
  CALIBRATION_LCT_DELAY_loc, COMP_MODE_loc, COMP_TIMING_loc,
  DMB_CRATE_ID_loc, DMB_CSCID_loc, DMB_CSC_KEY_loc, DMB_KEY_loc, 
  DMB_SLOT_loc,
  FEB_CLOCK_DELAY_loc, FEB_DAV_DELAY_loc, INJECT_DELAY_loc,
  INJECT_DAC_SET_loc, L1A_DAV_DELAY_loc, PRE_BLOCK_END_loc,
  PULSE_DELAY_loc, PULSE_DAC_SET_loc, PUSH_DAV_DELAY_loc,
  SET_COMP_THRESH_loc, TMB_DAV_DELAY_loc, XLATENCY_loc
};
