#!/bin/bash


cp TestBeamCrateController_orig.cc ../../PeripheralCrate/src/common/TestBeamCrateController.cc
cp testbeamcontrol_orig.cpp ../../PeripheralCrate/test/common/testbeamcontrol.cpp


  if [ $1 == 'd360' ] 
  then
    cp Makefile_emudcs_d360 ../Makefile
    cp Makefile_pc_d360 ../../PeripheralCrate/Makefile
  else  
    cp Makefile_emudcs_osu ../Makefile
    cp Makefile_pc_osu ../../PeripheralCrate/Makefile
  fi

cd ../../PeripheralCrate
make
make tests
cd ../e2p
make clean
make
