#!/bin/bash



#exit


#cp Makefile_emudcs_new ../Makefile


#####cd ../../PeripheralCore
#####make

#####cd ../PeripheralCrate
#####make

cd ../e2p
make clean
make
make tests
mv test/linux/x86_slc4/DcsEmuConfig.exe test/linux/x86_slc4/simple_config_plus_dcs_new.exe

