XDAQ_BACK_TO_ROOT:=../..

include $(XDAQ_BACK_TO_ROOT)/config/mfAutoconf.rules

Project=emu

include $(XDAQ_ROOT)/config/mfDefs.$(XDAQ_OS)

Packages= emuDAQ/emuReadout emuDAQ/emuFU emuDAQ/emuRUI emuDAQ/emuTA emuDAQ/emuDAQManager emuDAQ/emuClient emuDAQ/emuUtil

include $(XDAQ_ROOT)/config/Makefile.rules
