# standards
INCLUDE		= /usr/src/linux/include
CC 		= gcc
CFLAGS 		= -D__KERNEL__ -I$(INCLUDE) -DMODULE -Wall -O2

TARGET	= eth_hook_2
SRC	= eth_hook_2.c

all: $(TARGET).o

clean:
	rm -f *.o *~ core


