##
#
# This is the TriDAS/emu/emuDAQ/drivers/modules1OSUcc
#
##


XDAQ_BACK_TO_ROOT:=$(XDAQ_ROOT)
include $(XDAQ_BACK_TO_ROOT)/config/mfAutoconf.rules
include $(XDAQ_ROOT)/config/mfDefs.$(XDAQ_OS)

Project=emu
Package=emuDCS/drivers/modules1OSUcc

include $(XDAQ_ROOT)/config/Makefile.rules

_all:
	sh ./compile

_cleanall:
	rm *.o
