#!/bin/bash

# source this file from fast_daq directory

RCFILE=~cscme11/.zshrc
[ -z "${ROOTSYS}" ] && `grep "export ROOTSYS=" $RCFILE` && source ${ROOTSYS}/bin/thisroot.sh
[ -z "${XDAQ_OS}" ] && export XDAQ_OS=linux
[ -z "${XDAQ_PLATFORM}" ] && export XDAQ_PLATFORM=x86_64_slc5
[ -z "${XDAQ_ROOT}" ] && `grep "export XDAQ_ROOT=" $RCFILE`

export TRIDASDIST=~cscme11/TriDAS
export EMUDIST=$TRIDASDIST/emu
export BUILD_HOME=../calibration/../../dqm/../../emu/../
if [ -d  "$BUILD_HOME" ]; then
    export BUILD_HOME=`pwd | sed -e 's?emu/dqm/calibration$??g'`
    extraBin=${BUILD_HOME}/${XDAQ_PLATFORM}/bin
    [[ ":${PATH}:" =~ ":${extraBin}:" ]] || echo add ${extraBin} && export PATH=$PATH:${extraBin}
    extraBin=${TRIDASDIST}/${XDAQ_PLATFORM}/bin
    [[ ":${PATH}:" =~ ":${extraBin}:" ]] || echo add ${extraBin} && export PATH=$PATH:${extraBin}

    extraLib=${BUILD_HOME}/${XDAQ_PLATFORM}/lib
    [[ ":${LD_LIBRARY_PATH}:" =~ ":${extraLib}:" ]] || echo add ${extraLib} && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${extraLib}
    extraLib=${TRIDASDIST}/${XDAQ_PLATFORM}/lib
    [[ ":${LD_LIBRARY_PATH}:" =~ ":${extraLib}:" ]] || echo add ${extraLib} && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${extraLib}
else 
    echo ERROR BUILD_HOME DOES NOT EXIST
fi
export USELOCALBUILD=yes

