#!/bin/sh

PWD=`pwd`
/sbin/ifdown eth2
/sbin/rmmod acenic
/sbin/rmmod eth_hook
/sbin/modprobe crc32
/sbin/insmod $PWD/eth_hook.o
/sbin/insmod $PWD/acenic.o
/sbin/ifup eth2
/sbin/ifconfig eth2 -arp mtu 9000
