##
#
# This is the TriDAS/emu/emuDAQ/drivers/
#
##


XDAQ_BACK_TO_ROOT:=$(XDAQ_ROOT)
include $(XDAQ_BACK_TO_ROOT)/config/mfAutoconf.rules
include $(XDAQ_ROOT)/config/mfDefs.$(XDAQ_OS)

Project=emu
Package=emuDAQ/drivers/OSUcc_and_DDU

include $(XDAQ_ROOT)/config/Makefile.rules

_all:
	compile

_cleanall:
	rm *.o


