/********************************************************************
* CHistogramDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CHistogramDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableCHistogramDict();
extern void G__cpp_setup_inheritanceCHistogramDict();
extern void G__cpp_setup_typetableCHistogramDict();
extern void G__cpp_setup_memvarCHistogramDict();
extern void G__cpp_setup_globalCHistogramDict();
extern void G__cpp_setup_memfuncCHistogramDict();
extern void G__cpp_setup_funcCHistogramDict();
extern void G__set_cpp_environmentCHistogramDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "CHistogram.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CHistogramDictLN_TClass;
extern G__linked_taginfo G__CHistogramDictLN_TBuffer;
extern G__linked_taginfo G__CHistogramDictLN_TMemberInspector;
extern G__linked_taginfo G__CHistogramDictLN_TObject;
extern G__linked_taginfo G__CHistogramDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__CHistogramDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CHistogramDictLN_TH1;
extern G__linked_taginfo G__CHistogramDictLN_CObject;
extern G__linked_taginfo G__CHistogramDictLN_CHistogram;

/* STUB derived class for protected member access */
