/********************************************************************
* CObjectDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CObjectDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableCObjectDict();
extern void G__cpp_setup_inheritanceCObjectDict();
extern void G__cpp_setup_typetableCObjectDict();
extern void G__cpp_setup_memvarCObjectDict();
extern void G__cpp_setup_globalCObjectDict();
extern void G__cpp_setup_memfuncCObjectDict();
extern void G__cpp_setup_funcCObjectDict();
extern void G__set_cpp_environmentCObjectDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "CObject.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CObjectDictLN_TClass;
extern G__linked_taginfo G__CObjectDictLN_TBuffer;
extern G__linked_taginfo G__CObjectDictLN_TMemberInspector;
extern G__linked_taginfo G__CObjectDictLN_TObject;
extern G__linked_taginfo G__CObjectDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__CObjectDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CObjectDictLN_TString;
extern G__linked_taginfo G__CObjectDictLN_TVirtualPad;
extern G__linked_taginfo G__CObjectDictLN_CObject;

/* STUB derived class for protected member access */
