/********************************************************************
* HistoDisplayDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error HistoDisplayDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableHistoDisplayDict();
extern void G__cpp_setup_inheritanceHistoDisplayDict();
extern void G__cpp_setup_typetableHistoDisplayDict();
extern void G__cpp_setup_memvarHistoDisplayDict();
extern void G__cpp_setup_globalHistoDisplayDict();
extern void G__cpp_setup_memfuncHistoDisplayDict();
extern void G__cpp_setup_funcHistoDisplayDict();
extern void G__set_cpp_environmentHistoDisplayDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "HistoDisplay.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__HistoDisplayDictLN_TClass;
extern G__linked_taginfo G__HistoDisplayDictLN_TBuffer;
extern G__linked_taginfo G__HistoDisplayDictLN_TMemberInspector;
extern G__linked_taginfo G__HistoDisplayDictLN_TObject;
extern G__linked_taginfo G__HistoDisplayDictLN_TList;
extern G__linked_taginfo G__HistoDisplayDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__HistoDisplayDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__HistoDisplayDictLN_TString;
extern G__linked_taginfo G__HistoDisplayDictLN_TFile;
extern G__linked_taginfo G__HistoDisplayDictLN_TVirtualPad;
extern G__linked_taginfo G__HistoDisplayDictLN_TGObject;
extern G__linked_taginfo G__HistoDisplayDictLN_TGWindow;
extern G__linked_taginfo G__HistoDisplayDictLN_TQObject;
extern G__linked_taginfo G__HistoDisplayDictLN_TGFrame;
extern G__linked_taginfo G__HistoDisplayDictLN_TGCompositeFrame;
extern G__linked_taginfo G__HistoDisplayDictLN_TGLayoutHints;
extern G__linked_taginfo G__HistoDisplayDictLN_TGMainFrame;
extern G__linked_taginfo G__HistoDisplayDictLN_TGGroupFrame;
extern G__linked_taginfo G__HistoDisplayDictLN_TGMenuBar;
extern G__linked_taginfo G__HistoDisplayDictLN_TGPopupMenu;
extern G__linked_taginfo G__HistoDisplayDictLN_TGHorizontal3DLine;
extern G__linked_taginfo G__HistoDisplayDictLN_TGPictureButton;
extern G__linked_taginfo G__HistoDisplayDictLN_TGLabel;
extern G__linked_taginfo G__HistoDisplayDictLN_TGTextEntry;
extern G__linked_taginfo G__HistoDisplayDictLN_TGTextBuffer;
extern G__linked_taginfo G__HistoDisplayDictLN_TGTextButton;
extern G__linked_taginfo G__HistoDisplayDictLN_TGCheckButton;
extern G__linked_taginfo G__HistoDisplayDictLN_TGRadioButton;
extern G__linked_taginfo G__HistoDisplayDictLN_TGListTree;
extern G__linked_taginfo G__HistoDisplayDictLN_TGListTreeItem;
extern G__linked_taginfo G__HistoDisplayDictLN_TGCanvas;
extern G__linked_taginfo G__HistoDisplayDictLN_TH1;
extern G__linked_taginfo G__HistoDisplayDictLN_TH1F;
extern G__linked_taginfo G__HistoDisplayDictLN_TPad;
extern G__linked_taginfo G__HistoDisplayDictLN_TCanvas;
extern G__linked_taginfo G__HistoDisplayDictLN_TMapFile;
extern G__linked_taginfo G__HistoDisplayDictLN_TSocket;
extern G__linked_taginfo G__HistoDisplayDictLN_TGStatusBar;
extern G__linked_taginfo G__HistoDisplayDictLN_TConsumerInfo;
extern G__linked_taginfo G__HistoDisplayDictLN_ConsumerList;
extern G__linked_taginfo G__HistoDisplayDictLN_ConsumerListBox;
extern G__linked_taginfo G__HistoDisplayDictLN_CObject;
extern G__linked_taginfo G__HistoDisplayDictLN_HistoDisplayUpdateTimer;
extern G__linked_taginfo G__HistoDisplayDictLN_HistoDisplaySlideTimer;
extern G__linked_taginfo G__HistoDisplayDictLN_HistoDisplay;
extern G__linked_taginfo G__HistoDisplayDictLN_HistoDisplaycLcLEInputTypes;

/* STUB derived class for protected member access */
