/********************************************************************
* TConsumerInfoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TConsumerInfoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTConsumerInfoDict();
extern void G__cpp_setup_inheritanceTConsumerInfoDict();
extern void G__cpp_setup_typetableTConsumerInfoDict();
extern void G__cpp_setup_memvarTConsumerInfoDict();
extern void G__cpp_setup_globalTConsumerInfoDict();
extern void G__cpp_setup_memfuncTConsumerInfoDict();
extern void G__cpp_setup_funcTConsumerInfoDict();
extern void G__set_cpp_environmentTConsumerInfoDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "TConsumerInfo.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TConsumerInfoDictLN_TClass;
extern G__linked_taginfo G__TConsumerInfoDictLN_TBuffer;
extern G__linked_taginfo G__TConsumerInfoDictLN_TMemberInspector;
extern G__linked_taginfo G__TConsumerInfoDictLN_TObject;
extern G__linked_taginfo G__TConsumerInfoDictLN_TNamed;
extern G__linked_taginfo G__TConsumerInfoDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TConsumerInfoDictLN_TList;
extern G__linked_taginfo G__TConsumerInfoDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__TConsumerInfoDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TConsumerInfoDictLN_TString;
extern G__linked_taginfo G__TConsumerInfoDictLN_TSocket;
extern G__linked_taginfo G__TConsumerInfoDictLN_TConsumerInfo;
extern G__linked_taginfo G__TConsumerInfoDictLN_TConsumerInfocLcLdA;

/* STUB derived class for protected member access */
