#!/bin/sh -xv

duck_jar=$RCMS_HOME/framework/resourceservice/db/tools/parser/script/duck.jar

host=localhost
port=3306
name=rs3
user=rcms
type=MYSQL

if [[ $1 = --* ]]
then
    if [[ $1 = --usc55 ]]
    then
	host=oracms.cern.ch
	port=10121
	name=omds
	user=rs_csc
	type=ORACLE
    fi
    shift
fi

pass=$1
xml=$2

java -jar $duck_jar $xml $host $port $name $user $pass $type

